### ISSUE TITLE
The readme for sns-js confuses me.

### ISSUE THREAD

**Issue by e274426380** [dfinity/icp-js-canisters#452]
```
const snsWrapper: SnsWrapper = await initSnsWrapper({
  rootOptions: {
    canisterId: rootCanisterId,
  },
  agent,
  certified,
});

const { metadata: meta, swapState } = wrapper;
const [metadata, token] = await meta({});

console.log("Summary data:", metadata, token);
```
What is rootCanisterId?
I tried the Website asset canister(6hsbt-vqaaa-aaaaf-aaafq-cai) for openchat and it shows that **Canister 6hsbt-vqaaa-aaaaf-aaafq-cai has no update method 'list_sns_ canisters'.**
The SNS1 ledger canister id ( zfcdd-tqaaa-aaaaq-aaaga-cai) also does not work.
What is the correct example?
Speaking of which, why can't sns-js automatically look up the container id for SNS and import it? All the above container ids are a pain in the arse for me to find and import manually.

**Comment by e274426380** [comment]
> > What is rootCanisterId?
> 
> `rootCanisterId` as the canister ID of the `root` canister of a Sns. See for example a screenshot of OpenChat on the dashboard.
> 
> In the particular case of OC, the root canister ID is [3e3x2-xyaaa-aaaaq-aaalq-cai](https://dashboard.internetcomputer.org/canister/3e3x2-xyaaa-aaaaq-aaalq-cai).
> 
> > Speaking of which, why can't sns-js automatically look up the container id for SNS and import it? All the above container ids are a pain in the arse for me to find and import manually.
> 
> I actually does. See [Usage](https://github.com/dfinity/ic-js/tree/main/packages/sns#usage) in the README:
> 
> ```
> sns-js can be utilized with two distinct approaches. The first approach is explorative, where you only need to provide the SNS root canister ID of your project to initialize a wrapper that handles routing the calls to the appropriate canister. This means having a single entry point for all functions. 
> ```
> 
> i.e. if you initialize a wrapper with the root canister id the library will provide a single entry point to which "automatically look up the container id for SNS and import it".
> 
> For this purpose though you have indeed to use the appropriate root canister ID.
> 
> Hope this answer your question.
> 
> For sure if you think the README can be improved, feel free to provide a PR. Contribution much appreciated.
> 
> <img alt="Capture d’écran 2023-10-16 à 10 57 41" width="1536" src="https://user-images.githubusercontent.com/16886711/275450344-a70f56bc-72cc-4061-a994-05ee55b81af5.png">

This is probably the curse of knowledge.
The way I looked for the SNS root container was to look for the container ID in the SNS proposal in NNS instead of going to the dashboard, now I know.

**Comment by peterpeterparker** [comment]
> The way I looked for the SNS root container was to look for the container ID in the SNS proposal in NNS instead of going to the dashboard, now I know.

Gotcha! Yeah that can be confusing, don't know if there is a schema about what are the default Sns canisters and how they interact together. If they would be one we could reference it in the README...
